---
# FIXME: catch-all until this is further split into specific tasks
- name: UCI | Set fstab options
  uci:
    package: fstab
    section: '@global[0]'
    key: delay_root
    value: '10'

- name: UCI | Set ULA prefix
  uci:
    package: network
    section: 'globals'
    key: 'ula_prefix'
    value: "{{ openwrt_ula_prefix }}"
