---
# TODO: consume `uci export` as vars
# package dhcp
#
# config dnsmasq
# 	option domainneeded '1'
# 	option localise_queries '1'
# 	option rebind_protection '1'
# 	option rebind_localhost '1'
# 	option expandhosts '1'
# 	option authoritative '1'
# 	option readethers '1'
# 	option leasefile '/tmp/dhcp.leases'
# 	option resolvfile '/tmp/resolv.conf.auto'
# 	option localservice '1'
# 	option domain 'home.multicats.org'
# 	option local '/home.multicats.org/'
#
# config dhcp 'lan'
# 	option interface 'lan'
# 	option start '100'
# 	option limit '150'
# 	option leasetime '12h'
#
# config dhcp 'wan'
# 	option interface 'wan'
# 	option ignore '1'
#
# package dhcp-opkg
#
# config dnsmasq
# 	option domainneeded '1'
# 	option boguspriv '1'
# 	option filterwin2k '0'
# 	option localise_queries '1'
# 	option rebind_protection '1'
# 	option rebind_localhost '1'
# 	option local '/lan/'
# 	option domain 'lan'
# 	option expandhosts '1'
# 	option nonegcache '0'
# 	option authoritative '1'
# 	option readethers '1'
# 	option leasefile '/tmp/dhcp.leases'
# 	option resolvfile '/tmp/resolv.conf.auto'
# 	option nonwildcard '1'
# 	option localservice '1'
#
# config dhcp 'lan'
# 	option interface 'lan'
# 	option start '100'
# 	option limit '150'
# 	option leasetime '12h'
#
# config dhcp 'wan'
# 	option interface 'wan'
# 	option ignore '1'
#
# package dropbear
#
# config dropbear
# 	option PasswordAuth 'on'
# 	option RootPasswordAuth 'on'
# 	option Port '22'
# 	option Interface 'lan'
#
# package firewall
#
# config defaults
# 	option syn_flood '1'
# 	option input 'ACCEPT'
# 	option output 'ACCEPT'
# 	option forward 'REJECT'
# 	option drop_invalid '1'
#
# config zone
# 	option name 'lan'
# 	option input 'ACCEPT'
# 	option output 'ACCEPT'
# 	option forward 'ACCEPT'
# 	option network 'lan'
#
# config zone
# 	option name 'wan'
# 	option input 'REJECT'
# 	option output 'ACCEPT'
# 	option forward 'REJECT'
# 	option masq '1'
# 	option mtu_fix '1'
# 	option network 'wan wan6'
#
# config zone
# 	option name 'wifi'
# 	option input 'ACCEPT'
# 	option output 'ACCEPT'
# 	option network 'wifi WIFI'
# 	option forward 'ACCEPT'
#
# config forwarding
# 	option src 'lan'
# 	option dest 'wan'
#
# config forwarding
# 	option src 'wifi'
# 	option dest 'wan'
#
# config forwarding
# 	option src 'lan'
# 	option dest 'wifi'
#
# config rule
# 	option name 'Allow-DHCP-Renew'
# 	option src 'wan'
# 	option proto 'udp'
# 	option dest_port '68'
# 	option target 'ACCEPT'
# 	option family 'ipv4'
#
# config rule
# 	option name 'Allow-Ping'
# 	option src 'wan'
# 	option proto 'icmp'
# 	option icmp_type 'echo-request'
# 	option family 'ipv4'
# 	option target 'ACCEPT'
#
# config rule
# 	option name 'Allow-IGMP'
# 	option src 'wan'
# 	option proto 'igmp'
# 	option family 'ipv4'
# 	option target 'ACCEPT'
#
# config rule
# 	option name 'Allow-DHCPv6'
# 	option src 'wan'
# 	option proto 'udp'
# 	option src_ip 'fc00::/6'
# 	option dest_ip 'fc00::/6'
# 	option dest_port '546'
# 	option family 'ipv6'
# 	option target 'ACCEPT'
#
# config rule
# 	option name 'Allow-MLD'
# 	option src 'wan'
# 	option proto 'icmp'
# 	option src_ip 'fe80::/10'
# 	list icmp_type '130/0'
# 	list icmp_type '131/0'
# 	list icmp_type '132/0'
# 	list icmp_type '143/0'
# 	option family 'ipv6'
# 	option target 'ACCEPT'
#
# config rule
# 	option name 'Allow-ICMPv6-Input'
# 	option src 'wan'
# 	option proto 'icmp'
# 	list icmp_type 'echo-request'
# 	list icmp_type 'echo-reply'
# 	list icmp_type 'destination-unreachable'
# 	list icmp_type 'packet-too-big'
# 	list icmp_type 'time-exceeded'
# 	list icmp_type 'bad-header'
# 	list icmp_type 'unknown-header-type'
# 	list icmp_type 'router-solicitation'
# 	list icmp_type 'neighbour-solicitation'
# 	list icmp_type 'router-advertisement'
# 	list icmp_type 'neighbour-advertisement'
# 	option limit '1000/sec'
# 	option family 'ipv6'
# 	option target 'ACCEPT'
#
# config rule
# 	option name 'Allow-ICMPv6-Forward'
# 	option src 'wan'
# 	option dest '*'
# 	option proto 'icmp'
# 	list icmp_type 'echo-request'
# 	list icmp_type 'echo-reply'
# 	list icmp_type 'destination-unreachable'
# 	list icmp_type 'packet-too-big'
# 	list icmp_type 'time-exceeded'
# 	list icmp_type 'bad-header'
# 	list icmp_type 'unknown-header-type'
# 	option limit '1000/sec'
# 	option family 'ipv6'
# 	option target 'ACCEPT'
#
# config rule
# 	option name 'Allow-IPSec-ESP'
# 	option src 'wan'
# 	option dest 'lan'
# 	option proto 'esp'
# 	option target 'ACCEPT'
#
# config rule
# 	option name 'Allow-ISAKMP'
# 	option src 'wan'
# 	option dest 'lan'
# 	option dest_port '500'
# 	option proto 'udp'
# 	option target 'ACCEPT'
#
# config include
# 	option path '/etc/firewall.user'
#
# package fstab
#
# config global
# 	option anon_swap '0'
# 	option anon_mount '0'
# 	option auto_swap '1'
# 	option auto_mount '1'
# 	option check_fs '0'
# 	option delay_root '10'
#
# config mount
# 	option target '/overlay'
# 	option uuid 'e1a5ec08-6069-4f0a-b806-4d84129c7194'
# 	option enabled '1'
#
# config swap
# 	option device '/dev/sda4'
# 	option enabled '1'
#
# config mount
# 	option target '/overlay-boot'
# 	option device '/dev/mtdblock3'
# 	option fstype 'jffs2'
# 	option options 'rw,sync'
# 	option enabled '1'
# 	option enabled_fsck '0'
#
# config mount 'overlay'
# 	option uuid 'e431b16d-981f-4533-8f59-402a20a558f8'
# 	option target '/overlay'
#
# package luci
#
# config core 'main'
# 	option lang 'auto'
# 	option mediaurlbase '/luci-static/bootstrap'
# 	option resourcebase '/luci-static/resources'
#
# config extern 'flash_keep'
# 	option uci '/etc/config/'
# 	option dropbear '/etc/dropbear/'
# 	option openvpn '/etc/openvpn/'
# 	option passwd '/etc/passwd'
# 	option opkg '/etc/opkg.conf'
# 	option firewall '/etc/firewall.user'
# 	option uploads '/lib/uci/upload/'
#
# config internal 'languages'
#
# config internal 'sauth'
# 	option sessionpath '/tmp/luci-sessions'
# 	option sessiontime '3600'
#
# config internal 'ccache'
# 	option enable '1'
#
# config internal 'themes'
#
# config internal 'apply'
# 	option rollback '90'
# 	option holdoff '4'
# 	option timeout '5'
# 	option display '1.5'
#
# config internal 'diag'
# 	option dns 'openwrt.org'
# 	option ping 'openwrt.org'
# 	option route 'openwrt.org'
#
# package luci-opkg
#
# config core 'main'
# 	option lang 'auto'
# 	option mediaurlbase '/luci-static/bootstrap'
# 	option resourcebase '/luci-static/resources'
#
# config extern 'flash_keep'
# 	option uci '/etc/config/'
# 	option dropbear '/etc/dropbear/'
# 	option openvpn '/etc/openvpn/'
# 	option passwd '/etc/passwd'
# 	option opkg '/etc/opkg.conf'
# 	option firewall '/etc/firewall.user'
# 	option uploads '/lib/uci/upload/'
#
# config internal 'languages'
#
# config internal 'sauth'
# 	option sessionpath '/tmp/luci-sessions'
# 	option sessiontime '3600'
#
# config internal 'ccache'
# 	option enable '1'
#
# config internal 'themes'
#
# config internal 'apply'
# 	option rollback '90'
# 	option holdoff '4'
# 	option timeout '5'
# 	option display '1.5'
#
# package network
#
# config interface 'loopback'
# 	option ifname 'lo'
# 	option proto 'static'
# 	option ipaddr '127.0.0.1'
# 	option netmask '255.0.0.0'
#
# config globals 'globals'
# 	option ula_prefix 'fdee:2008:fd33::/48'
#
# config interface 'lan'
# 	option type 'bridge'
# 	option ifname 'eth0.1'
# 	option proto 'static'
# 	option netmask '255.255.255.0'
# 	option ipaddr '192.168.2.1'
# 	option dns '208.67.222.222 208.67.220.220'
# 	option gateway '192.168.1.2'
#
# config interface 'wan'
# 	option ifname 'eth0.2'
# 	option _orig_ifname 'eth0.2'
# 	option _orig_bridge 'false'
# 	option proto 'static'
# 	option netmask '255.255.255.0'
# 	option broadcast '255.255.255.255'
# 	option ipaddr '192.168.1.2'
# 	option gateway '192.168.1.1'
# 	list dns '192.168.1.3'
# 	list dns '9.9.9.9'
#
# config interface 'wan6'
# 	option ifname 'eth0.2'
# 	option proto 'dhcpv6'
#
# config switch
# 	option name 'switch0'
# 	option reset '1'
# 	option enable_vlan '1'
#
# config switch_vlan
# 	option device 'switch0'
# 	option vlan '1'
# 	option ports '2 3 4 5 0t'
#
# config switch_vlan
# 	option device 'switch0'
# 	option vlan '2'
# 	option ports '1 0t'
#
# config interface 'wifi'
# 	option _orig_ifname 'radio0.network1 wlan1'
# 	option _orig_bridge 'true'
# 	option proto 'static'
# 	option netmask '255.255.255.0'
# 	option gateway '192.168.0.2'
# 	option dns '192.168.0.1'
# 	option type 'bridge'
# 	option ipaddr '192.168.3.1'
#
# config route
# 	option interface 'wifi'
# 	option target '192.168.1.0'
# 	option netmask '255.255.255.0'
# 	option gateway '192.168.1.1'
#
# package rpcd
#
# config rpcd
# 	option socket '/var/run/ubus.sock'
# 	option timeout '30'
#
# config login
# 	option username 'root'
# 	option password '$p$root'
# 	list read '*'
# 	list write '*'
#
# package system
#
# config system
# 	option ttylogin '0'
# 	option log_size '64'
# 	option urandom_seed '0'
# 	option zonename 'Europe/Madrid'
# 	option timezone 'CET-1CEST,M3.5.0,M10.5.0/3'
# 	option log_proto 'udp'
# 	option cronloglevel '8'
# 	option conloglevel '5'
# 	option hostname 'owrt001.home.multicats.org'
#
# config timeserver 'ntp'
# 	option server '0.europe.pool.ntp.org 1.europe.pool.ntp.org 2.europe.pool.ntp.org 3.europe.pool.ntp.org 0.es.pool.ntp.org 1.es.pool.ntp.org 2.es.pool.ntp.org 3.es.pool.ntp.org'
#
# config led 'led_usb1'
# 	option name 'USB1'
# 	option sysfs 'tp-link:green:usb1'
# 	option trigger 'usbdev'
# 	option interval '50'
# 	option dev '1-1.1'
#
# config led 'led_usb2'
# 	option name 'USB2'
# 	option sysfs 'tp-link:green:usb2'
# 	option trigger 'usbdev'
# 	option interval '50'
# 	option dev '1-1.2'
#
# config led 'led_wlan2g'
# 	option name 'WLAN2G'
# 	option trigger 'phy0tpt'
# 	option sysfs 'tp-link:green:wlan2g'
#
# package ubootenv
#
# package ucitrack
#
# config network
# 	option init 'network'
# 	list affects 'dhcp'
# 	list affects 'radvd'
#
# config wireless
# 	list affects 'network'
#
# config firewall
# 	option init 'firewall'
# 	list affects 'luci-splash'
# 	list affects 'qos'
# 	list affects 'miniupnpd'
#
# config olsr
# 	option init 'olsrd'
#
# config dhcp
# 	option init 'dnsmasq'
# 	list affects 'odhcpd'
#
# config odhcpd
# 	option init 'odhcpd'
#
# config dropbear
# 	option init 'dropbear'
#
# config httpd
# 	option init 'httpd'
#
# config fstab
# 	option exec '/sbin/block mount'
#
# config qos
# 	option init 'qos'
#
# config system
# 	option init 'led'
# 	option exec '/etc/init.d/log reload'
# 	list affects 'luci_statistics'
# 	list affects 'dhcp'
#
# config luci_splash
# 	option init 'luci_splash'
#
# config upnpd
# 	option init 'miniupnpd'
#
# config ntpclient
# 	option init 'ntpclient'
#
# config samba
# 	option init 'samba'
#
# config tinyproxy
# 	option init 'tinyproxy'
#
# package uhttpd
#
# config uhttpd 'main'
# 	list listen_http '0.0.0.0:80'
# 	list listen_http '[::]:80'
# 	list listen_https '0.0.0.0:443'
# 	list listen_https '[::]:443'
# 	option redirect_https '1'
# 	option home '/www'
# 	option rfc1918_filter '1'
# 	option max_requests '3'
# 	option max_connections '100'
# 	option cert '/etc/uhttpd.crt'
# 	option key '/etc/uhttpd.key'
# 	option cgi_prefix '/cgi-bin'
# 	list lua_prefix '/cgi-bin/luci=/usr/lib/lua/luci/sgi/uhttpd.lua'
# 	option script_timeout '60'
# 	option network_timeout '30'
# 	option http_keepalive '20'
# 	option tcp_keepalive '1'
#
# config cert 'defaults'
# 	option days '730'
# 	option key_type 'rsa'
# 	option bits '2048'
# 	option ec_curve 'P-256'
# 	option country 'ZZ'
# 	option state 'Somewhere'
# 	option location 'Unknown'
# 	option commonname 'OpenWrt'
#
# package wireless
#
# config wifi-device 'radio0'
# 	option type 'mac80211'
# 	option hwmode '11g'
# 	option country 'ES'
# 	option distance '15'
# 	option channel '9'
# 	option htmode 'HT40'
# 	option path 'platform/ahb/18100000.wmac'
#
# config wifi-iface 'default_radio0'
# 	option device 'radio0'
# 	option mode 'ap'
# 	option ssid 'MULTICATS'
# 	option key 'zJWhfNa0zw5iMEJhu8n8'
# 	option network 'WIFI wifi'
# 	option encryption 'psk2+ccmp'
# 	option disabled '1'
#
# config wifi-device 'radio1'
# 	option type 'mac80211'
# 	option channel '36'
# 	option hwmode '11a'
# 	option path 'pci0000:00/0000:00:00.0'
# 	option htmode 'HT20'
# 	option country 'ES'
# 	option distance '15'
#
# config wifi-iface 'default_radio1'
# 	option device 'radio1'
# 	option mode 'ap'
# 	option ssid 'MULTICATS'
# 	option encryption 'psk2+ccmp'
# 	option key 'zJWhfNa0zw5iMEJhu8n8'
# 	option network 'WIFI wifi'
# 	option disabled '1'
#
# config wifi-device 'radio2'
# 	option type 'mac80211'
# 	option channel '11'
# 	option hwmode '11g'
# 	option htmode 'HT20'
# 	option disabled '1'
# 	option path 'platform/ahb/18100000.wmac'
#
# config wifi-iface 'default_radio2'
# 	option device 'radio2'
# 	option network 'lan'
# 	option mode 'ap'
# 	option ssid 'OpenWrt'
# 	option encryption 'none'
#
# FIXME: boilerplate code for helper
# - name: UCI | Set {{ item.package }}.{{ item.section }} options
#   uci:
#     package: {{ item.package }}
#     section: { item.package }}
#     name: { item.name }}
#     value: { item.value }}

- name: UCI | Set fstab options
  uci:
    package: fstab
    section: '@global[0]'
    key: delay_root
    value: '10'

- name: UCI | Set ULA prefix
  uci:
    package: network
    section: 'globals'
    key: 'ula_prefix'
    value: "{{ openwrt_ula_prefix }}"
